Pull 8-5
tomsloni/kodilla-8 pull request #2
Opened 2016-12-14 00:31 UTC by tomsloni

2016-12-15 21:50 UTC, zdolny requested changes

2016-12-15 21:50 UTC, zdolny commented on zadanie_8_5/zadanie_8_5.html
> +<html>
dodaj doctype

2016-12-15 21:50 UTC, zdolny commented on zadanie_8_5/zadanie_8_5.html
> +		<meta charset='utf-8'>
dodaj title

2016-12-15 21:50 UTC, zdolny commented on zadanie_8_5/zadanie_8_5.js
> +
wyswietl tez wynik oprocz tego czy jest dodatni itd

2016-12-15 21:50 UTC, zdolny commented on zadanie_8_5/zadanie_8_5.js
> +	console.log('wynik dodatni');
tu chyba powinno byc 'ujemny'

2016-12-15 21:50 UTC, zdolny commented on zadanie_8_5/zadanie_8_5.js
> +}
Sugeruje pewne udoskonalenie. Teraz jak wpisze niepoprawne dane np litery to otrzymuje jakis wynik, a chcialbym dostawac informacje "wynik nieokreslony"

2016-12-18 15:33 UTC, tomsloni commented
Poprawione.

2016-12-18 23:38 UTC, merged