Pull 8-6
tomsloni/kodilla-8 pull request #3
Opened 2016-12-14 00:32 UTC by tomsloni

2016-12-15 22:05 UTC, zdolny requested changes

2016-12-15 22:05 UTC, zdolny commented on zadanie_8_6/zadanie_8_6.html
> +<html>
dodaj doctype

2016-12-15 22:05 UTC, zdolny commented on zadanie_8_6/zadanie_8_6.html
> +		<meta charset='utf-8'>
dodaj tag title (jest obowiazkowy)

2016-12-15 22:05 UTC, zdolny commented on zadanie_8_6/zadanie_8_6.js
> +document.write(' Pole 3: ' + triangle3Area);
jesli uzywasz document.write to zadbaj tez o czytelnosc - obecnie wszystko jest w jednej linii

2016-12-18 15:48 UTC, tomsloni commented
Poprawione.

2016-12-18 23:40 UTC, merged