Pull 8-9
tomsloni/kodilla-8 pull request #6
Opened 2016-12-14 00:33 UTC by tomsloni

2016-12-15 22:36 UTC, zdolny requested changes
dodaj plik html

2016-12-18 16:02 UTC, tomsloni commented
Poprawione.

2016-12-19 21:50 UTC, zdolny requested changes
dodaj tez `var` do i, k, j

2016-12-19 21:50 UTC, zdolny commented on zadanie_8_9/zadanie_8_9.js
> +console.log(rysujChoinke(wiersze));
wywal console.log (wyrzuca w konsoli `undefined`) - wystarczy wywolac funkcje

2016-12-19 21:50 UTC, zdolny commented on zadanie_8_9/zadanie_8_9.js
> +var wiersze = prompt('Podaj liczbę wierszy: ')
dodaj srednik

2016-12-19 21:50 UTC, zdolny commented on zadanie_8_9/zadanie_8_9.js
> +		}
ten `for` jest zbedny

2016-12-20 21:14 UTC, zdolny requested changes

2016-12-20 21:14 UTC, zdolny commented on zadanie_8_9/zadanie_8_9.js
> +	j;
dobra praktyka nakazuje, zeby powyzsze linie (ale patrz dalej) znalazly sie wewnatrz funkcji, poniewaz nalezy to do jej funkcjonalnosci.

2016-12-20 21:14 UTC, zdolny commented on zadanie_8_9/zadanie_8_9.js
> +	for (i = 1, star = ''; i-1 != n; i++) {
deklaracje `star = ''` dalbym poza forem
*proponuje zmienne do liczenia (i, k, j) zadeklarowac wewnatrz for (dodac po prostu var)

2016-12-20 21:14 UTC, zdolny commented on zadanie_8_9/zadanie_8_9.js
> +		for (k = ((n*2-1) - (i*2-1))/2; k > 0; k -= 1) {
informacyjnie, mozna tez troche prosciej:
`for (var k = 0; k <= n-i-1; k++) {`

2016-12-21 00:28 UTC, merged