Pull 8-11
tomsloni/kodilla-8 pull request #8
Opened 2016-12-14 00:34 UTC by tomsloni

2016-12-15 22:55 UTC, zdolny requested changes

2016-12-15 22:55 UTC, zdolny commented on zadanie_8_11/8-11.html
> +<html>
dodaj doctype

2016-12-15 22:55 UTC, zdolny commented on zadanie_8_11/8-11.html
> +		<meta charset='utf-8'>
dodaj tag title

2016-12-15 22:55 UTC, zdolny commented on zadanie_8_11/8-11.js
> +}
ta funkcja nie jest uzywana - do uwalenia

2016-12-15 22:55 UTC, zdolny commented on zadanie_8_11/8-11.js
> +var inputElem = document.getElementById('addElem');
zmien nazwe zmiennej z `inputElem` na cos co bardziej wskazuje przeznaczenie czyli np `add`, `addElem` itp.

2016-12-15 22:55 UTC, zdolny commented on zadanie_8_11/8-11.js
> +	newElem = document.createElement('li');
te dwa przypisania zrob poza funkcja, zeby zwiekszyc performance. Niepotrzebnie teraz za kazdym wywolaniem funkcji pobierasz z DOMu te same elementy. Dodaj srednik na koncu.

2016-12-15 22:55 UTC, zdolny commented on zadanie_8_11/8-11.js
> +	i++;
zmienna `i` utworz (poza funkcja) pobierajac wszystkie tagi `li`, wtedy wewnatrz funkcji bedziesz mogl podstawiac ich aktualna ilosc przed dodaniem nowego `li` poprzez `items.length`

2016-12-18 16:33 UTC, tomsloni commented on zadanie_8_11/8-11.js
> +	newElem = document.createElement('li');
newElem chyba nie mogę wprost wypchnąć poza funkcję, bo będzie nadpisywać ciągle jeden i ten sam element

2016-12-18 16:33 UTC, tomsloni commented
Poprawione

2016-12-20 21:20 UTC, zdolny commented on zadanie_8_11/8-11.js
> +	newElem = document.createElement('li');
masz racje, sorry, moj blad

2016-12-20 21:20 UTC, merged